services:
  db:
    container_name: db
    image: 'postgres:16.4-bullseye'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourney-hub-db
    ports:
      - "5432:5432"
    volumes:
      - tourney-hub-db-volume:/var/lib/postgresql/data

volumes:
  tourney-hub-db-volume: